activities/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  
  resources :preload do
    resource :users
  end
  
  post "preload/new", to: "preload#create"
  patch 'preload/:id/edit', to: 'preload#update'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

activities/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

activities/app/models/preload.rb
class Preload < ApplicationRecord
    has_many :users, dependent: :destroy
end

activities/app/models/user.rb
class User < ApplicationRecord
end

activities/app/controllers/a_controller.rb
class AController < ApplicationController
end

activities/app/controllers/add_controller.rb
class AddController < ApplicationController
    def create
        @preload = Preload.find(params[:preload_id])
        @user = @preload.users.create(user_params)
        redirect_to preload_path(@preload)
    end
    
    private
    def user_params
        params.require(:user).permit(:zip, :body)
    end
end

activities/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def index
    end
end

activities/app/controllers/preload_controller.rb
class PreloadController < ApplicationController
    def index
        @active = Preload.all
        @user = User.all
    end
    
    def new
        @active = Preload.new
    end
    
    def show
        @active = Preload.find(params[:id])
    end
    
    def create
        @active = Preload.new(preload_params)
        
        if @active.save
            redirect_to @active
        else
            render 'new'
        end
    end
    
    def edit
        @active = Preload.find(params[:id])
    end
    
    def update
        @active = Preload.find(params[:id])
        
        if @active.update(preload_params)
            redirect_to @active
        else
            render 'edit'
        end 
    end
    
    def destroy
        @active = Preload.find(params[:id])
        @active.destroy
        
        redirect_to preload_index_path
    end
    
    
end

private
    def preload_params
        params.require(:preload).permit(:title, :text)
    end

activities/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def create
        @preload = Preload.find(params[:preload_id])
        @user = @preload.users.create(user_params)
        redirect_to preload_path(@preload)
    end
    
    def destroy
        @preload = Preload.find(params[:id])
        @user = @preload.users.find(params[:id])
        @user.destroy
        
        redirect_to preload_index_path
    end
    
    private
    def user_params
        params.require(:user).permit(:zip, :body)
    end
end

activities/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

activities/app/helpers/add_helper.rb
module AddHelper
end

activities/app/helpers/application_helper.rb
module ApplicationHelper
end

activities/app/helpers/preload_helper.rb
module PreloadHelper
end

activities/app/helpers/users_helper.rb
module UsersHelper
end

activities/app/helpers/welcome_helper.rb
module WelcomeHelper
end

activities/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Activities</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

activities/app/views/preload/edit.html.erb
<h1>Editing Activity</h1>
 
<%= form_for :preload, url: edit_preload_path(@active), method: :patch do |f| %>
 
  <% if @active.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@active.errors.count, "error") %> prohibited
        this activity from being saved:
      </h2>
      <ul>
        <% @active.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <p>
        <h2>Activity Zip Code</h2>
        <%= f.text_field :title %>
    </p>
    
    <p>
        <h2>Activity Title/Description</h2>
        <%= f.text_area :text %>
    </p>
    
    <p>
        <%= f.submit "Save Activity" %>
    </p>
 
<% end %>
 
<%= link_to 'Back', preload_index_path %>

activities/app/views/preload/index.html.erb
<h1>Listing Activities by Location</h1>
<div>
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign Out" , signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Google" , "/auth/google_oauth2" , id: "sign_in" %>
  <% end %>
</div>
<h2>Choose an Activity Location by Zip</h2>
<table>
  <% @active.each do |preload| %>
    <tr>
      <td><%= preload.title %> -- </td>
      <td><%= link_to 'View Activities', preload_path(preload.id) %> / </td>
      <td><%= link_to 'Edit Zip', edit_preload_path(preload.id) %> / </td>
      <td><%= link_to 'Delete Zip',
                              preload_path(preload.id),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<p>- or -</p>
<h2>Create a New Activity</h2>
<%= link_to 'New Activity', new_preload_path %>

activities/app/views/preload/new.html.erb
<h1>New Activity</h1>
<%= form_for :preload, url: new_preload_path do |f| %>
    <p>
        <h2>Activity Zip Code</h2>
        <%= f.text_field :title %>
    </p>
    
    <p>
        <h2>Activity Title/Description</h2>
        <%= f.text_area :text %>
    </p>
    
    <p>
        <%= f.submit "Save Activity" %>
    </p>
    
<% end %>

<%= link_to 'Back', preload_index_path %>

activities/app/views/preload/show.html.erb
<h2>Posted Activities at <%= @active.title %></h2>
<p>Below are activities that have already been posted at this location by the app!</p>

<ol>
    <li><strong><%= @active.text %></strong></li>
</ol>

<h2>User Added Activities</h2>
<p>Below are activities that have been posted by users!</p>
  <ol>
  <% @active.users.each do |user| %>
    <li><strong><%= user.body %></strong></li>
  <% end %>
  </ol>
  
<h2>Add an Activity at <%= @active.title %>:</h2>
<%= form_for([@active, @active.users.build]) do |f| %>
  <p>
    <%= f.label "Location" %><br>
    <%= f.text_field :zip %>
  </p>
  <p>
    <%= f.label "Activity Title/Description" %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit "Save Activity" %>
  </p>
<% end %>
<%= link_to 'Location List', preload_index_path %>

activities/app/views/welcome/index.html.erb
<h1>Welcome to the Charlotte Activity Generator</h1>
<h2>Head to our list of activities to see what's available by location!</h2>
<%= link_to 'Activity List', controller: 'preload' %>